# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/CIDE7/Ciencia-de-daos-iesb/blob/main/Untitled1.ipynb

Lista 2 de Exercícios Python
"""

nome = input("Digite seu nome completo: ")
print(nome.upper())
print(nome.lower())

frase = input("Digite uma frase com espaços no início e no fim: ")
print(frase.strip())

nome = input("Digite o nome do aluno: ")
linguagem = input("Digite a linguagem favorita: ")
print(f"O aluno {nome} tem como linguagem favorita o {linguagem}.")

locais = ["Brasília", "Goiânia", "São Paulo", "Rio de Janeiro", "Salvador"]
print(locais[2])

locais.append("Curitiba")
locais.pop(0)
print(locais)

numeros = list(range(1, 11))
print(numeros[2:8])

marcas = ("Toyota", "Honda", "Ford", "BMW")
# marcas[1] = "Chevrolet"
# ERRO: Tuplas são imutáveis, não é possível alterar seus elementos após a criação.

produto = {
    "nome": "Arroz",
    "categoria": "Alimento",
    "preco": 25.90
}
print(produto["preco"])

produto["preco"] = 27.50
produto["em_estoque"] = True
print(produto)

numero = int(input("Digite um número inteiro: "))
if numero % 2 == 0:
    print("PAR")
else:
    print("ÍMPAR")

idade = int(input("Digite sua idade: "))
if idade < 18:
    print("Menor de idade")
elif idade < 60:
    print("Adulto")
else:
    print("Idoso")

x = 5
y = 8
if x > 0 and y < 10:
    print("Valores válidos")
else:
    print("Valores fora do limite")

for i in range(0, 31):
    if i % 3 == 0:
        print(i)

disciplinas = ["Matemática", "Estatística", "Programação"]
for d in disciplinas:
    print(f"Eu preciso estudar {d}")

contador = 10
while contador >= 0:
    print(contador)
    contador -= 1
print("Decolar!")

cubos_pares = [x**3 for x in range(0, 11) if x % 2 == 0]
print(cubos_pares)

def saudacao_personalizada(nome):
    print(f"Seja muito bem-vindo(a) ao mundo dos dados, {nome}!")

saudacao_personalizada("Ana")

def calcula_desconto(valor, desconto):
    return valor - (valor * desconto / 100)

print(calcula_desconto(100, 10))

def classifica_nota(nota):
    if nota >= 7:
        return "Aprovado"
    elif nota >= 5:
        return "Recuperação"
    else:
        return "Reprovado"

print(classifica_nota(6.5))

numeros = [10, -3, 0, 5, -1, 0, 8, -7]

positivos = negativos = zeros = 0

for n in numeros:
    if n > 0:
        positivos += 1
    elif n < 0:
        negativos += 1
    else:
        zeros += 1

print(f"Positivos: {positivos}, Negativos: {negativos}, Zeros: {zeros}")